# Generated by Django 5.1.3 on 2024-11-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCrm', '0002_lead_message_lead_utm_campaign_lead_utm_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
