# Generated by Django 5.1.3 on 2024-11-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCrm', '0003_alter_lead_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_crm', models.CharField(max_length=100)),
                ('status_label', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=100)),
                ('procedure_name', models.CharField(max_length=100)),
                ('procedure_group', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('createdby_name', models.CharField(max_length=100)),
                ('createdby_created_at', models.DateTimeField()),
                ('appointment_date', models.DateTimeField()),
            ],
        ),
    ]
