# Generated by Django 5.1.3 on 2024-11-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCrm', '0004_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
