# Generated by Django 5.1.3 on 2024-11-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCrm', '0005_alter_appointment_customer_name_alter_lead_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_taxvat', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('store_name', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installments', models.IntegerField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField()),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('quote_items', models.TextField()),
            ],
        ),
    ]
