# Generated by Django 5.1.3 on 2024-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCrm', '0006_billcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcharge',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
