stores = {
        'ALPHAVILLE', 'BELO HORIZONTE', 'CAMPINAS', 'COPACABANA', 'ITAIM', 'IPIRANGA',
        'LAPA', 'LONDRINA', 'MOEMA', 'MOOCA', 'JARDINS', 'OSASCO', 'RIBEIRÃO PRETO',
        'SANTO AMARO', 'SANTOS', 'SOROCABA', 'TATUAPÉ', 'TIJUCA', 'TUCURUVI'
}